### ISSUE TITLE
A user can view an automatically sorted list of events/tasks

### ISSUE THREAD

**Issue by Braytongwm93** [cs2103aug2015-t10-1j/main#13]
...so that he can view his tasks, ranked in order of highest to lowest priority on each day for the next N days, at the first glance.

**Comment by Dartteon** [comment]
V0.1 -> Sorting by DAY -> TIME

V0.2 -> Sorting by DAY -> PRIORITY -> TIME

**Comment by gaobo9109** [comment]
Tasks will be automatically sorted by date and time
