### ISSUE TITLE
Storage - Create a function to specify the directory to save the text files in

### ISSUE THREAD

**Issue by Braytongwm93** [cs2103aug2015-t10-1j/main#48]
Got to do some research on this, not very familiar with how to code this. ^_^ "

**Comment by Braytongwm93** [comment]
It works! Now to implement it for the entire class.

**Comment by tlautrec** [comment]
yay!

**Comment by Braytongwm93** [comment]
Need more time to fully implement, especially with the use of changeDirectory.java().

**Comment by Braytongwm93** [comment]
Positive case is fully implemented. Now accounting for the case where the directory to be changed to already exists.

**Comment by Braytongwm93** [comment]
Fully implemented. Will implement similar feature to creating a directory when handling cases where a the specified directory already exists.

**Comment by Braytongwm93** [comment]
Yay done~
